// (old)agency/src/app/(temp)/home/page.tsx
import Image from "next/image";

export default function TemporaryHome() {
    return (
        <main className={`min-h-screen bg-black flex items-center justify-center lg:justify-start font-mono`}>
            {/* .content translation:
                - Mobile: flex-col, items-center, padding-4
                - Desktop (lg): flex-row, items-start, width-80%
            */}
            <div className="w-[90%] lg:w-[80%] p-4 lg:p-6 flex flex-col lg:flex-row items-center lg:items-start gap-10 lg:gap-[30px]">

                {/* Logo Container */}
                <div className="w-[220px] lg:w-[290px] flex justify-center lg:justify-start shrink-0">
                    <Image
                        src="/images/logo.png"
                        alt="LES GRIOTSxSTUDIO logo"
                        width={500}
                        height={500}
                        priority
                        className="w-full h-auto object-contain"
                    />
                </div>

                {/* Content Sections Container */}
                <div className="flex flex-col lg:flex-row gap-10 lg:gap-[30px] w-full text-center lg:text-left">

                    {/* Main Text Section */}
                    <div className="flex flex-col gap-4 font-mono text-[13px] lg:text-[16px] leading-[1.4] lg:leading-[1.6] uppercase tracking-wide text-white max-w-prose">
                        <p>
                            LESGRIOTSxSTUDIO is a transdisciplinary creative studio.
                        </p>
                        <p>
                            We combine artistic direction, movement, and audiovisual production
                            to design narratives that resonate across image, story, and
                            performance.
                        </p>
                        <p>
                            Our practice is rooted in Afro-diasporic perspectives and dedicated
                            to building cultural legacies through powerful visual storytelling.
                        </p>
                        <p>
                            We are driven by collaboration and thrive in creative environments
                            where meaning and impact are at the core.
                        </p>
                    </div>

                    {/* Services Section */}
                    <div className="flex flex-col gap-2 lg:gap-0 font-mono text-[13px] lg:text-[16px] leading-[1.4] lg:leading-[1.6] uppercase tracking-wide text-white whitespace-nowrap shrink-0">
                        <p className="underline decoration-1 underline-offset-4 mb-2 lg:mb-0">Services</p>
                        <p>Brand Strategy</p>
                        <p>Creative Direction</p>
                        <p>Production</p>
                    </div>

                    {/* Contacts Section */}
                    <div className="flex flex-col gap-2 lg:gap-0 font-mono text-[13px] lg:text-[16px] leading-[1.4] lg:leading-[1.6] uppercase tracking-wide text-white whitespace-nowrap shrink-0">
                        <p className="underline decoration-1 underline-offset-4 mb-2 lg:mb-0">Contacts</p>
                        <a
                            href="mailto:studio@Lesgriots.com"
                            className="hover:opacity-70 transition-opacity"
                        >
                            studio@Lesgriots.com
                        </a>
                    </div>

                </div>
            </div>
        </main>
    )
}

// agency/app/pages/home.vue
<script setup lang="ts">
// const { t } = useI18n()

// useSeoMeta({
// title: () => t('home.pageTitle'),
// description: () => t('pages.home.description'),
// })
</script>

<template>
    <div class="layout">
        <div class="content">
            <div class="logo-container">
                <img src="/images/logo.png" alt="LES GRIOTSxSTUDIO logo" class="logo" />
            </div>

            <div class="content-sections">
                <div class="main-text">
                    <p>
                        LESGRIOTSxSTUDIO is a transdisciplinary creative studio.
                    </p>

                    <p>
                        We combine artistic direction, movement, and audiovisual production to design narratives that
                        resonate across image, story, and performance.
                    </p>

                    <p>
                        Our practice is rooted in Afro-diasporic perspectives and dedicated to building cultural
                        legacies through powerful visual storytelling.
                    </p>

                    <p>
                        We are driven by collaboration and thrive in creative environments where meaning and impact are
                        at the core.
                    </p>
                </div>

                <div class="content-text no-wrap">
                    <p class="section-title">Services</p>
                    <p>Brand Strategy</p>
                    <p>Creative Direction</p>
                    <p>Production</p>
                </div>

                <div class="content-text no-wrap">
                    <p class="section-title">Contacts</p>
                    <a href="mailto:studio@Lesgriots.com">studio@Lesgriots.com</a>
                </div>
            </div>
        </div>
    </div>
</template>

<style scoped>
a,
p {
    color: white;
    font-size: 16px;
    line-height: 1.6;
    text-transform: uppercase;
    font-family: 'AkkuratMono', monospace;
}

.layout {
    background-color: black;
    min-height: 100vh;
    display: flex;
    justify-content: flex-start;
    align-items: center;
}

.content {
    display: flex;
    justify-content: start;
    align-items: flex-start;
    width: 80%;
    gap: 30px;
    padding: 24px;
}

.content-sections {
    display: flex;
    gap: 30px;
}

.main-text,
.content-text {
    display: flex;
    flex-direction: column;
}

.main-text {
    gap: 16px;
}

.logo-container {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 500px;
}

.logo {
    width: 100%;
    height: auto;
}

.section-title {
    text-decoration: underline;
}

.no-wrap {
    white-space: nowrap;
}

/* --- Responsive --- */

/* Tablette */
@media (max-width: 1024px) {
    .content {
        flex-direction: column;
        align-items: center;
        text-align: center;
        gap: 40px;
        width: 90%;
    }

    .content-sections {
        flex-direction: column;
        gap: 40px;
    }

    .logo-container {
        width: 300px;
    }

    a,
    p {
        font-size: 14px;
    }
}

/* Mobile */
@media (max-width: 600px) {
    .layout {
        justify-content: center;
    }

    .content {
        padding: 16px;
        gap: 24px;
    }

    .logo-container {
        width: 220px;
    }

    .content-text {
        gap: 10px;
    }

    a,
    p {
        font-size: 13px;
        line-height: 1.4;
    }

    .section-title {
        margin-top: 8px;
    }
}
</style>
